### ISSUE TITLE
How can I use multiple input streams?

### ISSUE THREAD

**Issue by OctaM** [bug-developer021/deepstream_python_nvdsanalytics_to_kafka#1]

**Comment by bug-developer021** [comment]
Hi! @OctaM , You can refer to  [deepstream_test_3.py](https://github.com/NVIDIA-AI-IOT/deepstream_python_apps/blob/master/apps/deepstream-test3/deepstream_test_3.py#L225-#L242)

It builds on deepstream-test1 to demonstrate how to:

- Use multiple sources in the pipeline

- Use a uridecodebin to accept any type of input (e.g. RTSP/File), any GStreamer supported container format, and any codec

- Configure Gst-nvstreammux to generate a batch of frames and infer on it for better resource utilization

- Extract the stream metadata, which contains useful information about the frames in the batched buffer
